language: node_js

addons:
  code_climate:
    repo_token: 63d80feaf8e54a36ade189584d878e0530cb597642749ee1a4a3ff1215304b50

before_script:
  - npm run build

script: npm run coverage

after_script:
  - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info

cache:
  directories:
    - node_modules
